services:
  springboot:
    image: ${CONTAINER_BASE_NAME}_springboot:latest
    container_name: ${CONTAINER_BASE_NAME}_springboot
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAVA_VERSION: 21.0.5-tem
        KOTLIN_VERSION: 1.8.0
        GRADLE_VERSION: 8.10.2
        U_ID: ${HOST_UID}
        G_ID: ${HOST_GID}
    environment:
      TERM: xterm-256color
    working_dir: /home/developer/work
    volumes:
      - ./work:/home/developer/work
