services:
  app:
    image: dev_kotlin_springboot:latest
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAVA_VERSION: 21.0.5-tem
        KOTLIN_VERSION: 1.8.0
        GRADLE_VERSION: 8.10.2
        SPRING_VERSION: 3.3.5
        U_ID: ${UID}
        G_ID: ${GID}
    environment:
      TERM: xterm-256color
    ports:
      - "${HOST_PORT}:8080"
    working_dir: /home/developer/work
    volumes:
      - ./work:/home/developer/work
