services:
  mysql:
    image: ${CONTAINER_BASE_NAME}_mysql:latest
    container_name: ${CONTAINER_BASE_NAME}_mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
      args:
        MYSQL_VERSION: latest
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    environment:
      TERM: xterm-256color
    user: "${HOST_UID}:${HOST_GID}"
    ports:
      - "${DATABASE_HOST_PORT}:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

  kotlin:
    image: ${CONTAINER_BASE_NAME}_kotlin:latest
    container_name: ${CONTAINER_BASE_NAME}_kotlin
    build:
      context: ./kotlin
      dockerfile: Dockerfile
      args:
        JAVA_VERSION: 21.0.5-tem
        KOTLIN_VERSION: 1.8.0
        GRADLE_VERSION: 8.10.2
        U_ID: ${HOST_UID}
        G_ID: ${HOST_GID}
    working_dir: /home/developer/work
    environment:
      TERM: xterm-256color
    volumes:
      - ./kotlin/work:/home/developer/work

  kotlin_springboot:
    image: ${CONTAINER_BASE_NAME}_kotlin_springboot:latest
    container_name: ${CONTAINER_BASE_NAME}_kotlin_springboot
    build:
      context: ./kotlin_springboot
      dockerfile: Dockerfile
      args:
        JAVA_VERSION: 21.0.5-tem
        KOTLIN_VERSION: 1.8.0
        GRADLE_VERSION: 8.10.2
        SPRING_VERSION: 3.3.5
        U_ID: ${HOST_UID}
        G_ID: ${HOST_GID}
    working_dir: /home/developer/work
    environment:
      TERM: xterm-256color
    ports:
      - "${KOTLIN_SPRINGBOOT_HOST_PORT}:8080"
    volumes:
      - ./kotlin_springboot/work:/home/developer/work

  go:
    image: ${CONTAINER_BASE_NAME}_go:latest
    container_name: ${CONTAINER_BASE_NAME}_go
    build:
      context: ./go
      dockerfile: Dockerfile
      args:
        JAVA_VERSION: 21.0.5-tem
        KOTLIN_VERSION: 1.8.0
        GRADLE_VERSION: 8.10.2
        U_ID: ${HOST_UID}
        G_ID: ${HOST_GID}
    working_dir: /home/developer/work
    environment:
      TERM: xterm-256color
    volumes:
      - ./go/work:/home/developer/work
