services:
  database:
    image: ${CONTAINER_BASE_NAME}_database:latest
    container_name: ${CONTAINER_BASE_NAME}_database
    build:
      context: ./database
      dockerfile: Dockerfile
      args:
        MYSQL_VERSION: 8.0.28
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    environment:
      TERM: xterm-256color
    ports:
      - "${DATABASE_HOST_PORT}:3306"
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d

  springboot:
    image: ${CONTAINER_BASE_NAME}_springboot:latest
    container_name: ${CONTAINER_BASE_NAME}_springboot
    build:
      context: ./springboot
      dockerfile: Dockerfile
      args:
        JAVA_VERSION: 21.0.5-tem
        KOTLIN_VERSION: 1.8.0
        GRADLE_VERSION: 8.10.2
        SPRING_VERSION: 3.3.5
        U_ID: ${HOST_UID}
        G_ID: ${HOST_GID}
    working_dir: /home/developer/work
    environment:
      TERM: xterm-256color
    ports:
      - "${SPRINGBOOT_HOST_PORT}:8080"
    volumes:
      - ./work:/home/developer/work
